### ISSUE TITLE
How to replay the animation？

### ISSUE THREAD

**Issue by chenxuuu** [ThatLousyGuy/Monolith#1]
when I run the animation once,I can't know how to replay it.
:(

**Comment by ThatLousyGuy** [comment]
Hmmm, it's been a long time since I've used this library, but sadly I think there's no convenient way to do this...
You can try this

    var anim = Noli.MoveXOf(elem).From(1).To(5);

After that you should be able to reuse `anim` by calling `anim.Now()` in different places.

You can also try triggering the animation again after it's finished and chaining them.

    EventToken anim2 = Noli.MoveYOf(elem).From(1).To(5).Now();
    EventToken nextToken = null;
    for (int i = 1; i < 10; ++i)
    {
        anim2 = Noli.MoveYOf(elem).From(1).To(5).After(anim2);
    }

Or (I definitely haven't tried this before) you can try grabbing the `Storyboard` object that's hidden in `EventToken` and play with the `RepeatBehavior` of that to get it to repeat.

    EventToken anim3 = Noli.MoveYOf(elem).From(1).To(5).Now();
    anim3.TokenStoryboard.RepeatBehavior = RepeatBehavior.Forever;
